/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BridgeAppRouteImport } from './routes/bridge-app'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TransactionIdRouteImport } from './routes/transaction.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeAppRoute = BridgeAppRouteImport.update({
  id: '/bridge-app',
  path: '/bridge-app',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const TransactionIdRoute = TransactionIdRouteImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/audit': typeof AuditRoute
  '/blog': typeof BlogRouteWithChildren
  '/bridge-app': typeof BridgeAppRoute
  '/contact': typeof ContactRoute
  '/landing': typeof LandingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/transactions': typeof TransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/audit': typeof AuditRoute
  '/bridge-app': typeof BridgeAppRoute
  '/contact': typeof ContactRoute
  '/landing': typeof LandingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/transactions': typeof TransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/audit': typeof AuditRoute
  '/blog': typeof BlogRouteWithChildren
  '/bridge-app': typeof BridgeAppRoute
  '/contact': typeof ContactRoute
  '/landing': typeof LandingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/transactions': typeof TransactionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/transaction/$id': typeof TransactionIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/audit'
    | '/blog'
    | '/bridge-app'
    | '/contact'
    | '/landing'
    | '/privacy-policy'
    | '/roadmap'
    | '/terms-of-service'
    | '/transactions'
    | '/blog/$slug'
    | '/transaction/$id'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/audit'
    | '/bridge-app'
    | '/contact'
    | '/landing'
    | '/privacy-policy'
    | '/roadmap'
    | '/terms-of-service'
    | '/transactions'
    | '/blog/$slug'
    | '/transaction/$id'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/audit'
    | '/blog'
    | '/bridge-app'
    | '/contact'
    | '/landing'
    | '/privacy-policy'
    | '/roadmap'
    | '/terms-of-service'
    | '/transactions'
    | '/blog/$slug'
    | '/transaction/$id'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AuditRoute: typeof AuditRoute
  BlogRoute: typeof BlogRouteWithChildren
  BridgeAppRoute: typeof BridgeAppRoute
  ContactRoute: typeof ContactRoute
  LandingRoute: typeof LandingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RoadmapRoute: typeof RoadmapRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TransactionsRoute: typeof TransactionsRoute
  TransactionIdRoute: typeof TransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge-app': {
      id: '/bridge-app'
      path: '/bridge-app'
      fullPath: '/bridge-app'
      preLoaderRoute: typeof BridgeAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/transaction/$id': {
      id: '/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof TransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AuditRoute: AuditRoute,
  BlogRoute: BlogRouteWithChildren,
  BridgeAppRoute: BridgeAppRoute,
  ContactRoute: ContactRoute,
  LandingRoute: LandingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RoadmapRoute: RoadmapRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TransactionsRoute: TransactionsRoute,
  TransactionIdRoute: TransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
