---
name: Unit Tests
on:
  pull_request:
  push:
    branches: 
      - main
      - feat/skyline

jobs:
  cardano_api_unit_test:
    name: Run Cardano-API Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.23.1
      - name: Install Cardano tools
        uses: milos-ethernal/cardano-node-action@5a3bce7266cc1500d96e8fa63b3bb97135988482
      - name: Run Go Test
        working-directory: ./cardano-api
        run: go test -race -timeout 20m ./...
